spring:
  application:
    name: dicom-proxy
  threads:
    virtual:
      enabled: true
  ssl:
    bundle:
      pem:
        dicom-bundle:
          keystore:
            certificate: "${CERTIFICATE_PATH:classpath:dummy.crt}"
            private-key: "${CERTIFICATE_PATH:classpath:dummy.key}"
            private-key-password: "${CERTIFICATE_PASSWORD:dummy}"
          truststore:
            certificate: "${CERTIFICATE_PATH:classpath:dummy.crt}"
          key:
            password: "${CERTIFICATE_PASSWORD:dummy}"
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 5GB
  datasource:
    url: "${POSTGRESQL_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dicom}"
    username: "${POSTGRESQL_DATASOURCE_USERNAME:postgres}"
    password: "${POSTGRESQL_DATASOURCE_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  elasticsearch:
    uris: "${SPRING_ELASTICSEARCH_URIS:https://localhost:9200}"
    username: "${SPRING_ELASTICSEARCH_USERNAME:elastic}"
    password: "${SPRING_ELASTICSEARCH_PASSWORD:password}"
    ca-path: "${CAPATH:/usr/share/app/certs/ca.crt}"

base-url: "${BASE_URL:http://localhost:8080}"

discord:
  webhook:
    url : "${DISCORD_WEBHOOK_URL:http://localhost}"

dicom:
  max-concurrency: "${MAX_DICOM_REQUEST:10}"
  purge:
    max-threads: "${PURGE_MAX_THREADS:5}"
  scp:
    enabled: "${DICOM_SCP_ENABLED:true}"
    aet: "${DICOM_SCP_AET:DICOM_PROXY}"
    port: "${DICOM_SCP_PORT:11112}"
    allowed-aets: "${DICOM_SCP_ALLOWED_AETS:ANY}"
    base-dir: "${DICOM_SCP_BASE_DIR:./dicom_store}"
    max-threads: "${DICOM_SCP_MAX_THREADS:10}"

server:
  port: 80

logging:
  level:
    dev.ioexception.dicom: DEBUG
