spring:
  application:
    name: dicom-proxy
  threads:
    virtual:
      enabled: true
  ssl:
    bundle:
      pem:
        dicom-bundle:
          keystore:
            certificate: "${CERTIFICATE_PATH}"
            private-key: "${CERTIFICATE_PATH}"
            private-key-password: "${CERTIFICATE_PASSWORD}"
          truststore:
            certificate: "${CERTIFICATE_PATH}"
          key:
            password: "${CERTIFICATE_PASSWORD}"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource-mysql:
    url: "${MYSQL_DATASOURCE_URL}"
    username: "${MYSQL_DATASOURCE_USERNAME}"
    password: "${MYSQL_DATASOURCE_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource-postgresql:
    url: "${POSTGRESQL_DATASOURCE_URL}"
    username: "${POSTGRESQL_DATASOURCE_USERNAME}"
    password: "${POSTGRESQL_DATASOURCE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  elasticsearch:
    uris: "${SPRING_ELASTICSEARCH_URIS:https://localhost:9200}"
    username: "${SPRING_ELASTICSEARCH_USERNAME:elastic}"
    password: "${SPRING_ELASTICSEARCH_PASSWORD:139413}"
    ca-path: "${CAPATH:/usr/share/app/certs/ca.crt}"

base-url: "${BASE_URL}"

discord:
  webhook:
    url : "${DISCORD_WEBHOOK_URL}"

dicom:
  scp:
    aet: "${DICOM_SCP_AET}"
    port: "${DICOM_SCP_PORT}"
    allowed-aets: "${DICOM_SCP_ALLOWED_AETS}"
    base-dir: "${DICOM_SCP_BASE_DIR}"
    max-threads: "${DICOM_SCP_MAX_THREADS}"

server:
  port: 80
